class Api::V1::Notification < ActiveRecord::Base
	TYPE_REPORT_LIKE = 'REPORT_LIKE'
	TYPE_REPORT_COMMENT = 'REPORT_COMMENT'
	TYPE_REPORT_PHOTO_LIKE = 'REPORT_PHOTO_LIKE'
	TYPE_REPORT_PHOTO_COMMENT = 'REPORT_PHOTO_COMMENT'
	TYPE_NEW_REPORT = 'REPORT_NEW'
	TYPE_FORECAST_ALERT = 'FORECAST_ALERT'
end